## Table captions
## Summary
caption_tab_ssu("ssu_beta_disp_tests", "Summary of Beta Dispersion Tests for unfiltered & filtered data sets against various distance metrics. The `test` column shows the method chosen (based on the test results) to assess differences in beta diversity. If p-values are significant (red, p-value < 0.05) we used ANOSIM, otherwise we used PERMANOVA (blue, p-value > 0.05).")
caption_tab_ssu("ssu_tab_sig_test_full", "Summary of significant tests by Year for FULL,   unfiltered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_ssu("ssu_tab_sig_test_filt", "Summary of significant tests by Year for Arbitrary filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_ssu("ssu_tab_sig_test_perfect", "Summary of significant tests by Year for PERFect filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_ssu("ssu_tab_sig_test_pime", "Summary of significant tests by Year for PIME filtered data set. P-values in red indicate significant differences (p-value < 0.05).")

caption_tab_its("its_beta_disp_tests", "Summary of Beta Dispersion Tests for unfiltered & filtered data sets against various distance metrics. The `test` column shows the method chosen (based on the test results) to assess differences in beta diversity. If p-values are significant (red, p-value < 0.05) we used ANOSIM, otherwise we used PERMANOVA (blue, p-value > 0.05).")
caption_tab_its("its_tab_sig_test_full", "Summary of significant tests by Year for FULL, unfiltered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_its("its_tab_sig_test_filt", "Summary of significant tests by Year for Arbitrary filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_its("its_tab_sig_test_perfect", "Summary of significant tests by Year for PERFect filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
caption_tab_its("its_tab_sig_test_pime", "Summary of significant tests by Year for PIME filtered data set. P-values in red indicate significant differences (p-value < 0.05).")
#<small>`r caption_tab_ssu("qual_scores_after_ssu")`</small>

## Figure captions
caption_fig_ssu("ssu_beta_div_plots_full", "PCoA ordination plots of the FULL data set. Top = phyloseq, bottom = microeco; Left = Jensen-Shannon Divergence, middle = UniFrac (unwieghted), right = UniFrac (wieghted).")
caption_fig_ssu("ssu_beta_div_plots_filt", "PCoA ordination plots of the Arbitrary filtered data set. Top = phyloseq, bottom = microeco; Left = Jensen-Shannon Divergence, middle = UniFrac (unwieghted), right = UniFrac (wieghted).")
caption_fig_ssu("ssu_beta_div_plots_perfect", "PCoA ordination plots of the PERfect filtered data set. Top = phyloseq, bottom = microeco; Left = Jensen-Shannon Divergence, middle = UniFrac (unwieghted), right = UniFrac (wieghted).")
caption_fig_ssu("ssu_beta_div_plots_pime", "PCoA ordination plots of the PIME filtered data set. Top = phyloseq, bottom = microeco; Left = Jensen-Shannon Divergence, middle = UniFrac (unwieghted), right = UniFrac (wieghted).")

caption_fig_ssu("ssu_ps_work_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_work_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_work_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_filt_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_filt_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_filt_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_perfect_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_perfect_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_perfect_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_pime_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_pime_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_ssu("ssu_ps_pime_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")

caption_fig_its("its_beta_div_plots_full", "PCoA ordination plots of the FULL data set. Top = phyloseq, bottom = microeco; Left = Jensen-Shannon Divergence, middle = Bray-Curtis dissimilarity, right = Gower distance.")
caption_fig_its("its_beta_div_plots_filt", "PCoA ordination plots of the Arbitrary filtered data set. Top = phyloseq, bottom = microeco; Left = Jensen-Shannon Divergence, middle = Bray-Curtis dissimilarity, right = Gower distance.")
caption_fig_its("its_beta_div_plots_perfect", "PCoA ordination plots of the PERfect filtered data set. Top = phyloseq, bottom = microeco; Left = Jensen-Shannon Divergence, middle = Bray-Curtis dissimilarity, right = Gower distance.")
caption_fig_its("its_beta_div_plots_pime", "PCoA ordination plots of the PIME filtered data set. Top = phyloseq, bottom = microeco; Left = Jensen-Shannon Divergence, middle = Bray-Curtis dissimilarity, right = Gower distance.")

caption_fig_its("its_ps_work_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_work_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_work_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the FULL data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_filt_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_filt_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_filt_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the Arbitrary filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_perfect_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_perfect_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_perfect_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the PERFect filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_pime_Y0_me_variation_plots", "Year 0 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_pime_Y1_me_variation_plots", "Year 1 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")
caption_fig_its("its_ps_pime_Y4_me_variation_plots", "Year 4 within (top) and between (bottom) group variation plots of the PIME filtered data set. Left to right: Jaccard, Jensen-Shannon, UniFrac (unweighted), UniFrac (weighted). Significant differences denoted by asterisks (\\* p < 0.05, \\*\\* p < 0.01, \\*\\*\\* p < 0.001, \\*\\*\\*\\* p < 0.0001).")


#<small>`r caption_fig_ssu("ssu_alpha_div_plots")`</small>
